version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
    env_file:
      - .env